# Generated by Django 6.0.3 on 2026-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="degree",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="typing_phrases",
            field=models.TextField(blank=True, help_text="One phrase per line"),
        ),
    ]
