# Generated by Django 6.0.3 on 2026-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_profile_degree_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_p1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_p2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_p3",
            field=models.TextField(blank=True),
        ),
    ]
